import { Annotation } from '@langchain/langgraph';

/**
 * Typed LangGraph State for NEXORA Repository Analysis Workflow
 */
export const AnalysisStateAnnotation = Annotation.Root({
  // Identifiers
  jobId: Annotation(),
  repositoryId: Annotation(),
  userId: Annotation(),
  commitSha: Annotation(),

  // Repository metadata & M6 deterministic facts
  repository: Annotation(),
  repositoryMetadata: Annotation(),
  codebaseFacts: Annotation(),

  // Domain-specific M8 RAG retrieved contexts
  retrievedContext: Annotation({
    reducer: (curr, update) => ({ ...(curr || {}), ...(update || {}) }),
    default: () => ({})
  }),

  // Domain analysis results generated by Groq / AI Provider
  technologies: Annotation(),
  technologyStack: Annotation(),
  architecture: Annotation(),
  modules: Annotation(),
  applicationFlow: Annotation(),
  summary: Annotation(),
  summaryData: Annotation(),

  // Final structured analysis object ready for persistence
  persistedRecord: Annotation(),
  finalAnalysis: Annotation(),

  // Workflow errors & diagnostics
  errors: Annotation({
    reducer: (curr, update) => (curr || []).concat(update || []),
    default: () => []
  })
});
